<?php
/**
 * Handles Comment Post to WordPress and prevents duplicate comment posting.
 *
 * @package WordPress
 */

nocache_headers();

if ( ! function_exists( 'wp_handle_upload' ) ) {
  require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

global $template_dir;
global $site_url;
global $is_logged_in;
global $current_user_id;

if (!$is_logged_in) { wp_redirect($site_url); exit; }

include_once $template_dir . '/functions/Game.php';

$location = $site_url;

$uploadedfile = $_FILES['file'];
$file_found = false;
$comment_data_toPost = [];
$upload_overrides = array(
    'test_form' => false
);

if ($_FILES['file']['error'] != 4) {
	$file_found = true;
}

if ( 'POST' !== $_SERVER['REQUEST_METHOD'] ) {
	$protocol = $_SERVER['SERVER_PROTOCOL'];
	if ( ! in_array( $protocol, array( 'HTTP/1.1', 'HTTP/2', 'HTTP/2.0' ), true ) ) {
		$protocol = 'HTTP/1.0';
	}

	header( 'Allow: POST' );
	header( "$protocol 405 Method Not Allowed" );
	header( 'Content-Type: text/plain' );
	exit;
}

// Post whatever comment we have
$comment = wp_insert_comment($_POST);

if (!$comment) {

	wp_die(
		'<p>' . 'Erro no envio. Tente de novo depois.' . '</p>',
		__( 'Erro no envio' ),
		array(
			'response'  => $data,
			'back_link' => true,
		)
	);

}

Guyra_increase_user_level($current_user_id, 2);

// Upload the attached image if it is found
if ($file_found) {
	$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
}

if ( $movefile && ! isset( $movefile['error'] ) ) {

	update_comment_meta($comment, 'comment_image', $movefile['url']);

} elseif ($file_found) {
    /*
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */

		wp_die(
			'<p>' . $movefile['error'] . '</p>',
			__( 'Erro no envio do arquivo' ),
			array(
				'response'  => $data,
				'back_link' => true,
			)
		);
}

$location = apply_filters( 'comment_post_redirect', $location, $comment );

if ($_POST['redirect']) {
  $location = $_POST['redirect'];
}

wp_safe_redirect( $location );
exit;
